# Generated by Django 5.1.4 on 2024-12-23 12:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("carbon", "0002_alter_agriculturalmaterial_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="agriculturalmaterial",
            options={},
        ),
        migrations.RemoveField(
            model_name="agriculturalmaterial",
            name="threshold",
        ),
        migrations.AlterField(
            model_name="agriculturalmaterial",
            name="name",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="agriculturalmaterial",
            name="quantity",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
