# Generated by Django 5.1.4 on 2024-12-23 19:59

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("community", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="customuser",
            options={},
        ),
        migrations.AlterModelTable(
            name="customuser",
            table="community_customuser",
        ),
    ]
