# Generated by Django 5.1.4 on 2024-12-23 20:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("community", "0002_alter_customuser_options_alter_customuser_table"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="customuser",
            options={"verbose_name": "user", "verbose_name_plural": "users"},
        ),
        migrations.AlterField(
            model_name="customuser",
            name="phone_number",
            field=models.CharField(
                blank=True, max_length=15, null=True, verbose_name="전화번호"
            ),
        ),
        migrations.AlterModelTable(
            name="customuser",
            table=None,
        ),
        migrations.DeleteModel(
            name="AgriculturalMaterial",
        ),
    ]
