# Generated by Django 5.1.2 on 2024-11-16 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0005_post_hook_text"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="hook_text",
        ),
        migrations.AddField(
            model_name="post",
            name="hook_test",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
