# Generated by Django 5.1.4 on 2024-12-22 08:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("community", "0002_blogpost_likes_blogpost_updated_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="blogpost",
            name="category",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
